### ISSUE TITLE
SPIKE - Trial API's for image generation

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#13]
**User Story**

As a user, I would like pictures in the story that are fun and unique so that I can have fun with the interactive story

**Acceptance Criteria**

* Trial several image APIs to see if using one in the code is fees able
* Document findings and demo to team

**Tasks**

- [x]  Research Pricing / Request Usage
- [x] Spike with code to see how it can be used in the project
- [x] QA Images to ensure it creates something near what we have asked for (although comedic affect, it can be off)
