### ISSUE TITLE
Create Start Section

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#20]
**User Story**

As a user I would like it to be immediately evident what the websites purpose is so I know if it interests me

**Acceptance Criteria**
 - Information on website present
 - Rules button present
 - Start button present

**Tasks**

- [x] Create the start section
- [x] Add in content
- [x] Create the buttons (no javascript needed for modal)
- [ ] Style the section
