### ISSUE TITLE
Create Rules Modal

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#21]
**User Story**
As a user I want to be able to see the game rules so that I understand how to play it

**Acceptance Criteria**

- Rules are displayed when Rules button is clicked

**Tasks**

- [ ] Create the rules
- [ ] Create the HTML modal
- [ ] Create the eventListener and attach to display the modal on click of the button
