### ISSUE TITLE
Create Story Board

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#22]
**User Story**
As a user I want to see my story played out and interactive with it so that I can be entertained

**Acceptance Criteria**

- Story page created with sections for dialogue, choices and epilogue

**Tasks**

- [ ] Create the story board section with relevant areas for story to be displayed
- [ ] Choices are buttons
- [ ] Styling for the page
