### ISSUE TITLE
Create End Screen

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#23]
**User Story**
As a user I want the story to have an end screen so that I can restart if I want to view a new story

**Acceptance Criteria**

- End page created with text & a way to get back to the home screen

**Tasks**

- [x] Add small , hard to read font on the end page thanking users for using our site
- [x] Using animations, flash up a scary image on screen after around 5 seconds
- [x] Add sound to trigger as soon as the image comes up
- [x] Ensure it's new pants needed scary
