### ISSUE TITLE
Create Story Selection Screen

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#25]
**User Story**
As a user I want to see the description of the story so I can make a selection

**Acceptance Criteria**

- Have a description on all cards
- Clickable cards start the story

**Tasks**

- [ ] Create 6 cards
- [ ] Populate synopsis of story
- [ ] Add image for each story
- [ ] Story cards are clickable
- [ ] Javascript loads the story selected
