### ISSUE TITLE
Integration: Merge all HTML files

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#54]
**Task**
Merge all HTML files into the index.html

**Acceptance Criteria**

- Application is now single page

**Tasks**

- [x] Merge all HTML files into one file, split into sections for start screen, selection screen and story board
- [x] Ensure main tag wraps all the content
- [x] Add javascript onclick functionality to hide and show sections based on the screens needed
- [x] For accessibility purposes, ensure each section has a heading
