### ISSUE TITLE
Take users name and format stories

### ISSUE THREAD

**Issue by Dee-McG** [Dee-McG/Hackathon-Project#66]
**User Story**

As a user, I want to be able to choose a character name for the story so that it can be tailored to that name

**Acceptance Criteria**

- User can create a character name that is used in stories with {char}

**Tasks**

- [ ] Take in a user input for character name for the story
- [ ] Store in session storage
- [ ] Iterate over story when selected and replace every {char} value with user name

**Comment by Mrst12** [comment]
not all the {char} names are being replaced in the story when you enter a username only on some screens
